# Loki values configuration placeholder

# Configures persistence for loki
loki:  
  schemaConfig:
    configs:
    - from: "2020-09-07"
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_index_
        period: 24h


  storageConfig:
    aws:
      s3: s3://lon1.digitaloceanspaces.com/junkyard
      access_key_id: ${TF_VAR_access_id}
      secret_access_key: ${TF_VAR_secret_key}
    boltdb_shipper:
      shared_store: s3
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
    filesystem:
      directory: /var/loki/chunks