# Prometheus values configuration placeholder

# Configures persistence for grafana instance
grafana:  
  persistence:
     enabled: true
     storageClassName: do-block-storage
     accessModes:
       - ReadWriteOnce
     size: 5Gi


# Ensures persistence for prometheus instance
prometheus:  
  prometheusSpec:    
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: do-block-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi